### ISSUE TITLE
2024年月末周六日历

### ISSUE THREAD

**Issue by shink** [shink/huawei-saturday#12]
```yaml
months:
    - 1
    - 3
    - 5
    - 6
    - 7
    - 8
    - 10
    - 12
days:
    - 01-01
    - 11-01
    - 12-31
```
